### PR TITLE
Attempt to bump from Chapel 1.16.0 to 1.18.0

### PR DESCRIPTION
**Pull request by bradcray**
I simply replaced the version numbers and am hoping everything
should "just work".  (I don't believe anything significant has
changed about our build system, so hopefully so).

### CODE REVIEW

**Comment by bradcray** [comment]
Hi @JonJagger --

We released a new version of Chapel today, and while refreshing the webpages, I realized that our version at Cyber-Dojo had grown quite stale.  This is my simplistic attempt to update things, but I can't recall whether there's an [easy] way for me to test prior to filing this pull request.  Let me know if there's more I can/should do.

Best wishes!
-Brad

**Comment by bradcray** [comment]
As a bonus, here's the heart of my answer for a parallel implementation to the "100 doors" challenge in Chapel:

```chapel
config const numDoors = 100;

var doorOpen: [1..numDoors] bool = false;

for step in 1..numDoors do
  forall i in 1..numDoors by step align step do
    doorOpen[i] = !doorOpen[i];

writeln(doorOpen);
```

**Comment by bradcray** [comment]
Hmm, Travis seems unhappy, though it looks like the Chapel build part of it went OK.  Give a shout if there's more I can do here to help.

**Comment by JonJagger** [comment]
Yes the Chapel part was all fine. Green now. And it triggered chapel-assert which is also green.
New image for chapel-assert now live on http://cyber-dojo.org
Thanks :-)

**Pull request merged**
